name: Compliance Monitor

on:
  push:
    branches: [ development, main ]
  workflow_dispatch: {}

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Monitor compliance
        run: node dist/cli/recipe-cli.js monitor-compliance || true
      - name: Upload dashboard artifact
        uses: actions/upload-artifact@v4
        with:
          name: compliance-dashboard
          path: docs/compliance-dashboard.html
      - name: Upload metrics
        uses: actions/upload-artifact@v4
        with:
          name: compliance-metrics
          path: performance-data/


